services:
  web:
    build: .
    deploy:
      replicas: 2
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=guest
      - MYSQL_DATABASE=devops_db
    networks:
      - devops-network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - devops-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: guest
      MYSQL_DATABASE: devops_db
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - devops-network

networks:
  devops-network:
